name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: landing.auditengine.org
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'exported_site'      # optional: defaults to entire repository  
        
    - name: Invalidate cloudfront cache
      run: |
        aws cloudfront create-invalidation --distribution-id E3G3GMQ6EMJJ9R  --paths "/*"
      
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # Access Key ID
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Access Secret Key
        AWS_S3_BUCKET: landing.auditengine.org # S3 bucket name
        SOURCE_DIR: "exported_site" # build folder
        # DEST_DIR: "landingsite" # destination subfolder within the bucket.
